# FROM fedora:33
#RUN dnf install -y gcc-c++ gcc make git \
#    bzip2 hwloc-devel blas blas-devel lapack lapack-devel boost-devel \
#    libatomic which vim-enhanced wget zlib-devel cmake \
#    python3-flake8 gdb sudo python3 python3-pip openmpi-devel sqlite-devel sqlite \
#    findutils openssl-devel papi papi-devel lm_sensors-devel tbb-devel \
#    xz bzip2 patch flex openssh-server \
#    texlive-xetex texlive-bibtex texlive-adjustbox texlive-caption texlive-collectbox \
#    texlive-enumitem texlive-environ texlive-eurosym texlive-jknapltx texlive-parskip \
#    texlive-pgf texlive-rsfs texlive-tcolorbox texlive-titling texlive-trimspaces \
#    texlive-ucs texlive-ulem texlive-upquote texlive-latex pandoc 
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt update -y && apt install -y bzip2 libhwloc-dev vim git gdb python3 python3-pip \
    libpapi-dev patch cmake libblas-dev liblapack-dev libtbb-dev patch npm \
    libglew-dev libboost-all-dev \
    t1-xfree86-nonfree ttf-xfree86-nonfree ttf-xfree86-nonfree-syriac xfonts-75dpi xfonts-100dpi \
    dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev imagemagick \
    && apt clean

ARG CPUS
ARG BUILD_TYPE

WORKDIR /
## ENV GCC_VER 8.4.0
## COPY install-from-spack.sh /usr/local/bin
## RUN bash /usr/local/bin/install-from-spack.sh
## COPY alternatives.sh /usr/local/bin
## RUN bash /usr/local/bin/alternatives.sh

# ENV AH_VER 4.6.0
# RUN curl -kLO https://www.dyninst.org/sites/default/files/downloads/harmony/ah-${AH_VER}.tar.gz
# RUN tar -xzf ah-${AH_VER}.tar.gz
# WORKDIR /activeharmony-${AH_VER}
# COPY ./activeharmony-4.6.0/code-server/code_generator.cxx code-server/code_generator.cxx
# RUN make CFLAGS=-fPIC LDFLAGS=-fPIC && make install prefix=/usr/local/activeharmony

# ENV OTF2_VER 2.1.1
# WORKDIR /
# RUN curl -kLO https://www.vi-hps.org/cms/upload/packages/otf2/otf2-${OTF2_VER}.tar.gz
# RUN tar -xzf otf2-${OTF2_VER}.tar.gz
# WORKDIR otf2-${OTF2_VER}
# RUN ./configure --prefix=/usr/local/otf2 --enable-shared && make && make install

#RUN ln -s /usr/lib64/openmpi/lib/libmpi_cxx.so /usr/lib64/openmpi/lib/libmpi_cxx.so.1
#RUN ln -s /usr/lib64/openmpi/lib/libmpi.so /usr/lib64/openmpi/lib/libmpi.so.12

#ENV PYVER 3.6.8
#WORKDIR /
#RUN wget https://www.python.org/ftp/python/${PYVER}/Python-${PYVER}.tgz
#RUN tar xf Python-${PYVER}.tgz
#WORKDIR /Python-${PYVER}
#RUN ./configure
#RUN make -j ${CPUS} install

## Make headers available
#RUN cp /Python-${PYVER}/pyconfig.h /Python-${PYVER}/Include
#RUN ln -s /Python-${PYVER}/Include /usr/include/python${PYVER}

#RUN pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org numpy tensorflow keras CNTK pytest
#RUN pip3 install numpy tensorflow keras CNTK pytest
WORKDIR /

#RUN dnf install -y python3-devel

WORKDIR /
RUN git clone --depth 1 https://github.com/pybind/pybind11.git && \
    mkdir -p /pybind11/build && \
    cd /pybind11/build && \
    cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DPYBIND11_PYTHON_VERSION=${PYVER} .. && \
    make -j ${CPUS} install && \
    rm -f $(find . -name \*.o)

RUN git clone --depth 1 https://bitbucket.org/blaze-lib/blaze.git && \
    cd /blaze && \
    mkdir -p /blaze/build && \
    cd /blaze/build && \
    cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && \
    make -j ${CPUS} install && \
    rm -f $(find . -name \*.o)

RUN git clone --depth 1 https://github.com/STEllAR-GROUP/blaze_tensor.git && \
    mkdir -p /blaze_tensor/build && \
    cd /blaze_tensor/build && \
    cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && \
    make -j ${CPUS} install && \
    rm -f $(find . -name \*.o)

WORKDIR /etc/skel
#COPY ./notebooks/*.ipynb ./
#RUN git clone --depth 1 https://github.com/shortcourse/USACM16-shortcourse
RUN git clone --depth 1 https://github.com/shortcourse/WCCM-APCOM-22
RUN find . | xargs -d '\n' chmod +r

#RUN dnf install -y nodejs psmisc tbb-devel
RUN pip3 install --upgrade pip
RUN pip3 install jupyter jupyterhub matplotlib numpy termcolor

#ENV DATE 2020-03-10
#RUN mkdir -p /usr/install/cling
#WORKDIR /usr/install/cling
#RUN git clone --branch cling-patches http://root.cern.ch/git/llvm.git src
#WORKDIR /usr/install/cling/src
#RUN git checkout ac712f0f44b45a1455a302dd6cbb7b6cce269d2d
#WORKDIR /usr/install/cling/src/tools
#RUN git clone http://root.cern.ch/git/cling.git
#WORKDIR /usr/install/cling/src/tools/cling
#RUN git checkout 2949bf96b71f9301247275a8097a060aae3429f4
#WORKDIR /usr/install/cling/src/tools
#RUN git clone --branch cling-patches http://root.cern.ch/git/clang.git
#WORKDIR /usr/install/cling/src/tools/clang
#RUN git checkout 25f804797f80b69d8c56794e3e0300acd9458958
RUN apt install -y conda
RUN conda config --set channel_priority strict
RUN conda create -c conda-forge --name rootenv root
RUN conda activate rootenv

### ORKDIR /usr/install/cling/src/tools/cling

### UN mkdir -p /usr/install/cling/src/build
### OPY Pipe.hpp /usr/local/include/
### OPY Augment_Kernel.hpp /usr/local/include
### OPY Kernel.cpp /usr/install/cling/src/tools/cling/tools/Jupyter

### ORKDIR /usr/install/cling/src/build
### UN cmake -DCMAKE_INSTALL_PREFIX=/usr \
###  -DCMAKE_BUILD_TYPE=Release \
###  -DCMAKE_CXX_FLAGS='-Wl,-s' \
###  -DLLVM_ENABLE_RTTI=ON \
###  -DLLVM_ENABLE_EH=ON \
###  /usr/install/cling/src
###  RUN dnf install -y patch
### ORKDIR /usr/install/cling/src
### OPY limits.patch .
### UN patch -p1 < limits.patch
### ORKDIR /usr/install/cling/src/tools/cling
### OPY noexcept.patch ./
### UN patch -p1 < noexcept.patch
### ORKDIR /usr/install/cling/src/build
### OPY make.sh /usr/install/cling/src/build/
### UN bash ./make.sh
### UN  cd /usr/install/cling/src/tools/cling/tools/Jupyter/kernel && \
###  pip3 install -e . && \
###  jupyter-kernelspec install cling-cpp17 && \
###  npm install -g configurable-http-proxy 
### ORKDIR /usr
### # ENV CLING cling_2020-11-05_ROOT-fedora32
### # ENV CLING_TARBALL ${CLING}.tar.bz2
### # RUN curl -LO https://root.cern/download/cling/${CLING_TARBALL} && \
### #     tar xjf ${CLING_TARBALL} && \
### #     rm -f ${CLING_TARBALL}
### # WORKDIR /usr/${CLING}/share/cling/Jupyter/kernel
### # RUN pip3 install -e . && \
### #     jupyter-kernelspec install cling-cpp17 && \
### #     npm install -g configurable-http-proxy && \
### #     ln -s /usr/${CLING}/bin/cling /usr/bin/cling

### UN git clone -b 1.8.1 --depth 1 https://github.com/STEllAR-GROUP/hpx.git /hpx
### ORKDIR /hpx
### UN mkdir -p /hpx/build
### ORKDIR /hpx/build
### RUN env CXX=$(which clang++) cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
### UN cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
###      -DHPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=ON \
###      -DHPX_WITH_CXX17_HARDWARE_DESTRUCTIVE_INTERFERENCE_SIZE=OFF \
###      -DHPX_WITH_FETCH_ASIO=ON \
###      -DHPX_WITH_BUILTIN_INTEGER_PACK=OFF \
###      -DHPX_WITH_ITTNOTIFY=OFF \
###      -DHPX_WITH_THREAD_COMPATIBILITY=ON \
###      -DHPX_WITH_MALLOC=system \
###      -DHPX_WITH_MORE_THAN_64_THREADS=ON \
###      -DHPX_WITH_MAX_CPU_COUNT=80 \
###      -DHPX_WITH_EXAMPLES=Off \
###      -DHPX_WITH_CXX_STANDARD=17 \
###      -DCMAKE_BUILD_TYPE=RelWithDebugInfo \
###      .. && \
###    make -j ${CPUS} install && \
###    rm -f $(find . -name \*.o)
### UN mkdir -p /hpx/build2
### ORKDIR /hpx/build2
### RUN env CXX=$(which clang++) cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
### UN cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
###      -DHPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=ON \
###      -DHPX_WITH_CXX17_HARDWARE_DESTRUCTIVE_INTERFERENCE_SIZE=OFF \
###      -DHPX_WITH_FETCH_ASIO=ON \
###      -DHPX_WITH_BUILTIN_INTEGER_PACK=OFF \
###      -DHPX_WITH_ITTNOTIFY=OFF \
###      -DHPX_WITH_THREAD_COMPATIBILITY=ON \
###      -DHPX_WITH_MALLOC=system \
###      -DHPX_WITH_MORE_THAN_64_THREADS=ON \
###      -DHPX_WITH_MAX_CPU_COUNT=80 \
###      -DHPX_WITH_EXAMPLES=Off \
###      -DHPX_WITH_CXX_STANDARD=20 \
###      -DHPX_WITH_DATAPAR_BACKEND=STD_EXPERIMENTAL_SIMD \
###      -DCMAKE_BUILD_TYPE=RelWithDebugInfo \
###      -DCMAKE_INSTALL_PREFIX=/usr/local/hpx-corot \
###      .. && \
###    make -j ${CPUS} install && \
###    rm -f $(find . -name \*.o)

### # RUN (make -j 8 install 2>&1 | tee make.out)
### OPY ./run_hpx.cpp /usr/include/run_hpx.cpp
### UN chmod 644 /usr/include/run_hpx.cpp

### UN pip3 install oauthenticator
### RUN dnf install -y procps cppcheck python3-pycurl sqlite python3-libs
### OPY ./login.html /usr/local/share/jupyterhub/templates/login.html
### OPY ./login2.html /root
### OPY ./stellar-logo.png /usr/local/share/jupyterhub/static/images/

### NV PYTHONPATH /usr/local/python
### UN mkdir -p /usr/local/python
### OPY ./mkuser.py ${PYTHONPATH}/mkuser.py
### OPY ./mkuser.py /usr/local/bin/mkuser
### UN chmod 755 /usr/local/bin/mkuser
### UN pip3 install tornado #==5.1.1 # There's a bug in newer versions
### OPY ./clingk.py /usr/${CLING}/share/cling/Jupyter/kernel/clingkernel.py
### UN python3 -c 'import sys; print(sys.path[-1])' > /tmp/path.txt
### OPY ./find.py ${PYTHONPATH}/
### OPY ./pipes1.py ${PYTHONPATH}/
### OPY ./pipes3.py ${PYTHONPATH}/
### OPY ./cling.py ${PYTHONPATH}/
### OPY ./py11.py ${PYTHONPATH}/
### UN python3 ${PYTHONPATH}/find.py > /usr/hpx-libs.txt
### RUN cp /Python-${PYVER}/pyconfig.h /Python-${PYVER}/Include
### RUN ln -s /Python-${PYVER}/Include /usr/include/python${PYVER}
### ORKDIR /

### UN git clone --depth 1 https://github.com/STEllAR-GROUP/BlazeIterative
### ORKDIR /BlazeIterative/build
### UN cmake ..
### UN make install

###  For some reason, HPX will not link in @py11() unless I do this
### UN ldconfig /usr/local/lib64

### ORKDIR /notebooks
### OPY ./notebk.sh ./

### ORKDIR /root
### UN chmod 755 .
### OPY ./startup.sh startup.sh
### OPY ./jup-config.py jup-config.py

###  For authentication if we aren't using OAuth
### UN git clone -b v1.2 --depth 1 https://github.com/stevenrbrandt/cyolauthenticator.git
### UN pip3 install git+https://github.com/stevenrbrandt/cyolauthenticator.git@v1.2

###  Use this CMD for a jupyterhub
###  CMD bash startup.sh

### OPY clingk.py /usr/install/cling/src/tools/cling/tools/Jupyter/kernel/clingkernel.py
###  RUN ln -s /usr/${CLING}/lib/libclingJupyter.so /usr/lib/libclingJupyter.so
###  RUN ln -s /usr/${CLING}/lib/clang /usr/lib/clang
###  RUN ln -s /usr/${CLING}/include/cling /usr/include/cling
### UN echo "export PYTHONPATH=${PYTHONPATH}" >> /etc/bashrc
### RUN dnf install -y ImageMagick file hostname
### OPY is_expr.py /usr/local/python
### OPY cin.py /usr/local/python
### OPY logo.png /usr/local/share/jupyterhub/static/images/
### OPY teleplot.hpp /usr/include

### OPY ./Dockerfile /Dockerfile
###  Not sure why this makes sense
### UN ln -s /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0 /usr/lib64/libboost_system.so.1.0.0
### UN python3 -m pip install piraha==1.1.7

### OPY ./notebooks/*.ipynb /etc/skel/
### UN useradd -m jovyan -s /bin/bash
### SER jovyan
### ORKDIR /home/jovyan
### NV LD_LIBRARY_PATH /home/jovyan/install/phylanx/lib64:/usr/local/lib64:/home/jovyan/install/phylanx/lib/phylanx:/usr/lib64/openmpi/lib

### UN mkdir -p /home/jovyan/bot
### OPY bot/cxxbot.py /home/jovyan/bot/
### OPY bot/teleplot.py /home/jovyan/bot/
### OPY bot/telecling.py /home/jovyan/bot/
### OPY bot/thumbsup.png /home/jovyan/bot/
### OPY bot/colored.py /home/jovyan/bot/
### UN pip3 install --user randpass python-telegram-bot

### ORKDIR /home/jovyan
### OPY nb.py /root/
### OPY hpxcxx /usr/local/bin/
### OPY vector_pack_type.hpp /usr/local/include/hpx/execution/traits/detail/simd/vector_pack_type.hpp
### MD bash /notebooks/notebk.sh
